### ISSUE TITLE
Progress Bar Update - Spinner Icon

### ISSUE THREAD

**Issue by ravenusmc** [mezerotm/cmv#18]
When the progress bar loads and it moves from the left hand side of the screen to the right, it will go back to the left hand side and start all over. The bar should be set up so that when it reaches the right hand side, the map is loaded.

**Comment by NJTuley** [comment]
We can't do this. This would require us to know exactly how long it would take for the citysdk request to send us back a response, which depends on 1) User's internet speed, 2) CitySDK server responsivity, and other reasons, and we aren't able to know this. The best we could do is have it freeze at say, 25% or 50% and wait there until it finishes, then move it to 100%. I personally like it how it is, the motion shows that the page has not frozen to the user, and maintains their confidence that the page is working (even though it is just an arbitrarily moving bar). I think it serves its purpose as best it can for our web page

**Comment by ravenusmc** [comment]
Yeah, Carlos and I were talking about this. He thought that there may be a way to do it but your reasons Nick are what we were thinking as well-something that shows the user that the system has not timed out. If I remember correctly, Carlos said that his original purpose was basically that. If Carlos does know a way then I think give it a shot but more than likely you are right and we should close this task. Others thoughts?

**Comment by ravenusmc** [comment]
Should we close this task out?

**Comment by NJTuley** [comment]
In order to show the user best that their data request is being processed, and to which map the data is being processed for (and where the data will be output), the new plan is to have a spinning icon to show that they request is being sent to the citysdk servers, then the response is being processed and output to the active map.
 The spinning icon will be placed on top of the active map that the request is being processed for. When the user selects to send a new request for the data, the active map will be grayed out and the spinning icon will be placed as an overlay on top of the active map, and it will stay this way until all responses are retrieved, all data is processed, and all of that processed data is output to the map as an updated heatmap.
This will allow the user to both clearly and cleanly see that the data is being processed, and when the data is finished being processed and output, and to see more distinctly the data that was output to the map.
