### ISSUE TITLE
Allow user to save multiple queries/variables 

### ISSUE THREAD

**Issue by ravenusmc** [mezerotm/cmv#19]
When a user currently selects population and then wants to select income, the program will not hold the memory of the selection to income. This needs to be fixed so as to allow the user to see multiple variables across different maps.

**Comment by mezerotm** [comment]
I think you are on something here. You are right the user should be able to select different variables but saving their last selection I think is going about it all wrong. I think we should remove radio buttons and instead act as though every option was a submit button in itself so that when someone clicks on the variable in the sidebar-page the map immediately reacts to their clicks and starts populating the 'active' map with the selected variable.
