### ISSUE TITLE
Look at why we have a search bar.

### ISSUE THREAD

**Issue by ravenusmc** [mezerotm/cmv#24]
In the top left hand side of the home screen there is a search bar. Why is it there? Is there a plan to use this at all? Something to relook at. If it has not purpose then purge it out.

**Comment by mezerotm** [comment]
We had a search bar to be able to accommodate more variables since getting a large number of variables would require ALOT of html (this is future thinking, that in the future we plan on expanding the variables) we could also use ES6 to help with html templating to automate the html variables, if you don't konw what templating is here is a JS framwork? that is very popular that does it https://goo.gl/rCiEe (keep in mind this existed before ES6, so it's more of a legacy framework now..)

**Comment by hardnett** [comment]
I see. My vote is that we remove the search bar for the alpha release and move this issue to the beta release for further discussion.

**Comment by ravenusmc** [comment]
I agree, I think we should have the search bar removed for this release.

**Comment by mezerotm** [comment]
@ravenusmc; 
@NJTuley  is using the search bar for #26
